events {}

http {

    include /etc/nginx/mime.types;

    default_type application/octet-stream;

    sendfile on;

    # ==================================================
    # STREAMING
    # ==================================================

    # Muy importante para SSE
    proxy_buffering off;

    # ==================================================
    # FRONTEND
    # ==================================================

    upstream frontend {
        server frontend:5173;
    }

    # ==================================================
    # BACKEND
    # ==================================================

    upstream backend {
        server ai-api:11343;
    }

    server {

        listen 80;

        server_name _;


        # ==================================================
        # FRONTEND
        # ==================================================

        location / {

            proxy_pass http://frontend;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }


        # ==================================================
        # FASTAPI
        # ==================================================

        location /api/ {

            proxy_pass http://backend;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Streaming / SSE
            proxy_buffering off;
            proxy_cache off;

            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;

            proxy_set_header Connection "";

            add_header X-Accel-Buffering no;
        }
    }
}